Library/Library/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Library.Models
{
    public class Book
    {
        public long Id { get; set; }

        public string Name { get; set; }

        public string Genre { get; set; }

        public string Author { get; set; }

        public string Publisher { get; set; }
    }
}

Library/Library/Controllers/BooksController.cs
using BusinessLayer.Interfaces;
using BusinessLayer.Models.BookDTO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Threading.Tasks;

namespace Library.Controllers
{

    public class BooksController : Controller
    {
        private readonly IBookService bookService;
        private readonly IWebHostEnvironment _appEnvironment;
        const string librarian = "Библиотекарь";

        public BooksController(IBookService bookService, IWebHostEnvironment appEnvironment)
        {
            this.bookService = bookService;
            _appEnvironment = appEnvironment;
        }

        // Фильтрация книг.
        public async Task<IActionResult> Index(string bookGenre, string bookAuthor, string bookPublisher, string searchString)
        {
            var bookSearchVM = await bookService.BookSearchAsync(bookGenre, bookAuthor, bookPublisher, searchString);

            return View(bookSearchVM);
        }

        // GET создание книги.
        [Authorize(Roles = librarian)]
        public IActionResult Create()
        {
            return View();
        }

        // POST создание книги.
        [Authorize(Roles = librarian)]
        [HttpPost]
        public async Task<IActionResult> CreateBook(BookViewModel book, IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                var uploadedFileName = uploadedFile.FileName;
                var path = "/Files/" + uploadedFileName;

                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

                bookService.CreateBook(book, path, uploadedFileName);
            }

            return RedirectToAction("Index");
        }

        // GET редактирование книги.
        [Authorize(Roles = librarian)]
        [HttpGet]
        public IActionResult Edit(long id)
        {
            var model = bookService.EditBookGet(id);

            return View(model);
        }

        // POST редактирование книги.
        [Authorize(Roles = librarian)]
        [HttpPost]
        public async Task<IActionResult> Edit(EditBookViewModel bookModel, IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                var uploadedFileName = uploadedFile.FileName;
                var path = "/Files/" + uploadedFileName;

                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }

                bookService.EditBookPost(bookModel, path, uploadedFileName);
            }

            return RedirectToAction("Index");
        }

        // Удаление книги.
        [Authorize(Roles = librarian)]
        public ActionResult Delete(long id)
        {
            bookService.Delete(id);

            return RedirectToAction("Index");
        }

        // Подробнее о книге.
        public IActionResult Details(long id)
        {
            BookViewModel book = bookService.GetBook(id);

            return View(book);
        }
    }
}

Library/Library/Controllers/OrdersController.cs
using BusinessLayer.Interfaces;
using DataLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Library.Controllers
{
    public class OrdersController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IOrderService orderService;

        const string client = "Клиент";
        const string librarian = "Библиотекарь";

        public OrdersController(UserManager<User> userManager, IOrderService orderService)
        {
            this.userManager = userManager;
            this.orderService = orderService;
        }

        // Бронирование книги.
        public async Task<IActionResult> Booking(long id)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);
            orderService.CreateOrder(id, user);

            return RedirectToAction("UserOrders");
        }

        // Брони клиента.
        [Authorize(Roles = client)]
        public IActionResult UserOrders()
        {
            var userId = userManager.GetUserId(HttpContext.User);
            var orders = orderService.GetUserOrders(userId);

            return View(orders);
        }

        // Все брони.
        [Authorize(Roles = librarian)]
        public IActionResult AllOrders()
        {
            var orders = orderService.GetAllOrders();

            return View(orders);
        }

        // Отмена брони/возвращение книги.
        public ActionResult Delete(long id)
        {
            orderService.DeleteOrder(id);

            if (this.User.IsInRole(client))
            {
                return RedirectToAction("UserOrders");
            }
            else
            {
                return RedirectToAction("AllOrders");
            }
        }

        // Отчача книги клиенту.
        public ActionResult Pass(long id)
        {
            orderService.PassBook(id);

            return RedirectToAction("AllOrders");
        }
    }
}

Library/Library/Views/Books/Create.cshtml
@using BusinessLayer.Models.BookDTO;
@model BookViewModel
@{
    ViewBag.Title = "Добавление книги";
}

<form asp-action="CreateBook" asp-controller="Books" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Genre" class="control-label">Жанр</label>
        <input type="text" asp-for="Genre" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Author" class="control-label">Автор</label>
        <input type="text" asp-for="Author" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Publisher" class="control-label">Издательство</label>
        <input type="text" asp-for="Publisher" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание</label>
        <textarea asp-for="Description" rows="10" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label class="control-label">Обложка</label>
        <input type="file" name="uploadedFile" /><br>

    </div>

    <div class="form-group">
        <input type="submit" value="Добавить" class="btn btn-default" />
    </div>
</form>

Library/Library/Views/Books/Details.cshtml
@using BusinessLayer.Models.BookDTO;
@model BookViewModel
@{
    ViewBag.Title = Model.Name;
}

<h2> @Model.Name</h2>

@if (User.IsInRole("Библиотекарь"))
{
    <a asp-action="Edit" asp-controller="Books" asp-route-id="@Model.Id"> Изменить </a>
    <a asp-action="Delete" asp-controller="Books" asp-route-id="@Model.Id"> Удалить </a>
}

<div>
    <img width="300" height="500" src="@Model.ImgPath" />

    <dl class="dl-horizontal">
        <dd>
            @if (User.IsInRole("Клиент") && Model.BookStatus == DataLayer.Enums.BookStatus.Available)
            {
                <a asp-action="Booking" asp-controller="Orders" asp-route-id="@Model.Id"> Забронировать</a>
            }
        </dd>

        <dt>Название книги</dt>
        <dd>@Html.DisplayFor(modelItem => Model.Name)</dd>

        <dt>Жанр</dt>
        <dd>@Html.DisplayFor(modelItem => Model.Genre)</dd>

        <dt>Автор</dt>
        <dd>@Html.DisplayFor(modelItem => Model.Author)</dd>

        <dt>Издательство</dt>
        <dd>@Html.DisplayFor(modelItem => Model.Publisher)</dd>

        <dt>Описание</dt>
        <dd>@Html.DisplayFor(modelItem => Model.Description)</dd>

        <dt>Статус</dt>
        <dd>@Html.DisplayFor(modelItem => Model.BookStatus)</dd>

        <dd><a asp-action="Index" asp-controller="Books"> Список книг</a></dd>
    </dl>
</div>

Library/Library/Views/Books/Edit.cshtml
@using BusinessLayer.Models.BookDTO; 
@model EditBookViewModel
@{
    ViewBag.Title = "Редактирование книги";
}
<form asp-action="Edit" asp-controller="Books" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>

    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Genre" class="control-label">Жанр</label>
        <input type="text" asp-for="Genre" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Author" class="control-label">Автор</label>
        <input type="text" asp-for="Author" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Publisher" class="control-label">Издательство</label>
        <input type="text" asp-for="Publisher" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание</label>
        <textarea asp-for="Description" rows="10" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label class="control-label">Обложка</label>
        <input type="file" name="uploadedFile" /><br>
    </div>

    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>

Library/Library/Views/Books/Index.cshtml
@using BusinessLayer.Models.BookDTO;
@using DataLayer.Enums; 
@model BookSearchViewModel
@{
    ViewBag.Title = "Список книг";
}

<h2><strong>Книги</strong></h2>

@if (this.User.IsInRole("Библиотекарь"))
{
    <form asp-controller="Books" asp-action="Create">
        <input type="submit" value="Добавить книгу" />
    </form>
}

<form asp-controller="Books" asp-action="Index" method="get">
    <p>
        <select asp-for="BookGenre" asp-items="Model.Genres">
            <option value="">Жанр (все)</option>
        </select>

        <select asp-for="BookAuthor" asp-items="Model.Authors">
            <option value="">Автор (все)</option>
        </select>

        <select asp-for="BookPublisher" asp-items="Model.Publisher">
            <option value="">Издательство (все)</option>
        </select>

        Название: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Найти" />
    </p>
</form>

<table class="table">
    <thead>
        <tr bgcolor="#D3D3D3">
            <td><strong>Название</strong></td>
            <td><strong>Жанр</strong></td>
            <td><strong>Автор</strong></td>
            <td><strong>Издательство</strong></td>
            <td><strong>Доступность</strong></td>
            <td></td>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Books)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Publisher)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookStatus)
                </td>

                @if (this.User.IsInRole("Библиотекарь"))
                {
                    <td>
                        <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                            <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                            <button type="submit" class="btn btn-sm btn-danger">
                                Удалить
                            </button>
                        </form>
                    </td>
                }

                @if (this.User.IsInRole("Клиент"))
                {
                    @if (item.BookStatus == BookStatus.Available)
                    {
                        <td>
                            <form method="get" asp-route-id="@item.Id" asp-controller="Orders" asp-action="Booking">
                                <input type="submit" value="Забронировать" />
                            </form>
                        </td>
                    }
                }
            </tr>
        }
    </tbody>
</table>